name = "ai-crm-erp"
compatibility_date = "2026-08-29"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "ad7c15ef18114a7aa90f175f88dd3f24"
